# -*- coding: utf-8 -*-
"""PETM_Wafer map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zF60P_YQzqh0oikK0uaZ5CACfnnLeUd
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from PIL import Image
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
import os, warnings, numpy as np, pandas as pd

# %matplotlib inline

import os
print(os.listdir("/content/drive/MyDrive/dataset"))
import warnings
warnings.filterwarnings("ignore")

df=pd.read_pickle("/content/drive/MyDrive/dataset/LSWMD.pkl")
df.info()

df.head()

uni_Index=np.unique(df.waferIndex, return_counts=True)
plt.bar(uni_Index[0],uni_Index[1], color='green', align='center', alpha=0.5)
plt.title("wafer index distribution")
plt.xlabel("index number")
plt.ylabel("freq")
plt.xlim(0,26)
plt.ylim(30000,34000)
plt.show()

df['failureNum']=df.failureType
df['trainTestNum']=df.trianTestLabel
mapping_type={'Center':0, 'Donut':1, 'Edge-Loc':2, 'Edge-Ring':3, 'Loc':4, 'Random':5,'Scratch':6, 'Near-full':7, 'none':8}
mapping_traintest={'Training':0, 'Test':1}
df=df.replace({'failureNum':mapping_type, 'trainTestNum':mapping_traintest})

# -----------------------------
# 1. 사용자 정의 Dataset 클래스
# -----------------------------
class WaferDataset(Dataset):
    def __init__(self, df: pd.DataFrame, transform=None):
        self.df = df
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_array = row["waferMap"]  # 이미 numpy array일 것
        label = int(row["failureNum"])

        # [H, W] → [H, W, 3] (1채널을 3채널로 복제)
        if isinstance(img_array, np.ndarray) and img_array.ndim == 2:
            img_array = np.stack([img_array]*3, axis=-1)  # (H, W, 3)

        img = Image.fromarray(img_array.astype(np.uint8))  # numpy → PIL 이미지

        if self.transform:
            img = self.transform(img)

        return img, label

pkl_path = "/content/drive/MyDrive/dataset/LSWMD.pkl"  # ★ PKL 파일 경로
assert os.path.exists(pkl_path), f"PKL not found: {pkl_path}"

df = pd.read_pickle(pkl_path)

# split 열 처리 (trainTestLabel or trianTestLabel 자동 감지)
if "trainTestLabel" in df.columns:
    split_col = "trainTestLabel"
elif "trianTestLabel" in df.columns:
    split_col = "trianTestLabel"
else:
    raise KeyError("train/test 라벨 컬럼이 없습니다.")

# 라벨 처리 함수
def clean_split_label(x):
    if isinstance(x, (list, np.ndarray)):
        if len(x) == 0:
            return None
        if isinstance(x[0], (list, np.ndarray)):
            return str(x[0][0]).strip() if len(x[0]) > 0 else None
        elif isinstance(x[0], str):
            return x[0].strip()
    elif isinstance(x, str):
        return x.strip()
    return None

def clean_failure_type(x):
    if isinstance(x, (list, np.ndarray)):
        if len(x) == 0:
            return None
        if isinstance(x[0], str):
            return x[0].strip()
    elif isinstance(x, str):
        return x.strip()
    return None

df["splitLabel_str"] = df[split_col].apply(clean_split_label)
df["failureType_str"] = df["failureType"].apply(clean_failure_type)

LABEL_MAP = {
    "Center": 0, "Donut": 1, "Edge-Loc": 2, "Edge-Ring": 3,
    "Loc": 4, "Random": 5, "Scratch": 6, "Near-full": 7, "none": 8
}
df["failureNum"] = df["failureType_str"].map(LABEL_MAP)

# 매핑 실패시 "none" 처리
missing = df["failureNum"].isna().sum()
if missing > 0:
    print(f"⚠️ {missing}개 라벨 매핑 실패 → 'none'(8)으로 대체")
    df.loc[df["failureNum"].isna(), "failureNum"] = LABEL_MAP["none"]

# split 매핑
df["trainTestNum"] = df["splitLabel_str"].map({"Training": 0, "Test": 1})
missing_tt = df["trainTestNum"].isna().sum()
if missing_tt > 0:
    print(f"⚠️ {missing_tt}개 split 매핑 실패 샘플 제거됨")
    df = df.dropna(subset=["trainTestNum"])
    df["trainTestNum"] = df["trainTestNum"].astype(int)

print(df["splitLabel_str"].value_counts())

train_df = df[df["trainTestNum"] == 0].reset_index(drop=True)
test_df  = df[df["trainTestNum"] == 1].reset_index(drop=True)
print(f"Train: {len(train_df)} | Test: {len(test_df)}")

# -----------------------------
# 3. transform & DataLoader
# -----------------------------
transform = transforms.Compose([
    transforms.Resize((32, 32)),     # 입력 크기 통일
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

train_loader = DataLoader(
    WaferDataset(train_df, transform), batch_size=64, shuffle=True, num_workers=2
)

test_loader = DataLoader(
    WaferDataset(test_df, transform), batch_size=64, shuffle=False, num_workers=2
)

# -----------------------------
# 4. 모델 정의 (BaseModel)
# -----------------------------
class BaseModel(nn.Module):
    def __init__(self):
        super(BaseModel, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(64 * 8 * 8, 256)
        self.fc2 = nn.Linear(256, 9)  # 9개 클래스

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = x.view(-1, 64 * 8 * 8)
        x = torch.relu(self.fc1(x))
        return self.fc2(x)

print(df.columns.tolist())

# -----------------------------
# 5. BaseModel 학습 (A)
# -----------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("DEVICE:", device)

model_A = BaseModel().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_A.parameters(), lr=0.001)

for epoch in range(10):
    model_A.train()
    running_loss = 0.0
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model_A(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"[Epoch {epoch+1}] Loss: {running_loss:.4f}")

torch.save(model_A.state_dict(), "base_model.pth")
print("✅ base_model.pth 저장 완료")

# -----------------------------
# 6. 오답 샘플 추출 (Dt_mis)
# -----------------------------
model_A.eval()
mis_inputs = []
mis_labels = []

with torch.no_grad():
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model_A(inputs)
        _, preds = torch.max(outputs, 1)
        mask = preds != labels

        if mask.any():
            mis_inputs.append(inputs[mask].cpu())
            mis_labels.append(labels[mask].cpu())

Dt_mis_inputs = torch.cat(mis_inputs)
Dt_mis_labels = torch.cat(mis_labels)
torch.save(Dt_mis_inputs, "Dt_mis_inputs.pt")
torch.save(Dt_mis_labels, "Dt_mis_labels.pt")
print(f"❌ 오답 샘플 저장 완료 ({Dt_mis_inputs.shape[0]}개)")

# -----------------------------
# 7. A′ 모델 학습 (Dt_mis로 과적합)
# -----------------------------
model_Aprime = BaseModel().to(device)
model_Aprime.load_state_dict(torch.load("base_model.pth"))

Dt_mis_dataset = torch.utils.data.TensorDataset(Dt_mis_inputs, Dt_mis_labels)
Dt_mis_loader = torch.utils.data.DataLoader(Dt_mis_dataset, batch_size=64, shuffle=True)

optimizer_aprime = optim.Adam(model_Aprime.parameters(), lr=0.001)

model_Aprime.train()
for epoch in range(10):
    running_loss = 0.0
    for inputs, labels in Dt_mis_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer_aprime.zero_grad()
        outputs = model_Aprime(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_aprime.step()

        running_loss += loss.item()

    print(f"[A′ Epoch {epoch+1}] Loss: {running_loss:.4f}")

torch.save(model_Aprime.state_dict(), "a_prime_model.pth")
print("✅ A′ 모델 저장 완료: a_prime_model.pth")