# -*- coding: utf-8 -*-
"""MC_dropout(FGSM).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pIE2fYPGEw_cXq7pORRMXbbyvyA1mj20
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import TensorDataset, DataLoader

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
trainset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True, num_workers=2)
testset = torchvision.datasets.MNIST(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False, num_workers=2)

class BaseModel(nn.Module):
    def __init__(self):
        super(BaseModel, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.dropout = nn.Dropout(p=0.5)  # MC Dropout 추가
        self.fc1 = nn.Linear(64 * 7 * 7, 256)
        self.fc2 = nn.Linear(256, 10)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = x.view(-1, 64 * 7 * 7)
        x = self.dropout(torch.relu(self.fc1(x)))  # dropout 활성화
        return self.fc2(x)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
base_model = BaseModel().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(base_model.parameters(), lr=0.001)

num_epochs = 10
for epoch in range(num_epochs):
    running_loss = 0.0
    for inputs, labels in trainloader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = base_model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    print(f"[Epoch {epoch+1}] Loss: {running_loss:.3f}")

torch.save(base_model.state_dict(), 'base_model.pth')
print("base_model 저장 완료: base_model.pth")

base_model.eval()
misclassified_inputs = []
misclassified_labels = []
total_samples = 0
incorrect_samples = 0

with torch.no_grad():
    for inputs, labels in trainloader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = base_model(inputs)
        _, predicted = torch.max(outputs, 1)
        incorrect_mask = predicted != labels
        if incorrect_mask.any():
            misclassified_inputs.append(inputs[incorrect_mask])
            misclassified_labels.append(labels[incorrect_mask])
            incorrect_samples += incorrect_mask.sum().item()
        total_samples += labels.size(0)

Dt_mis_inputs = torch.cat(misclassified_inputs, dim=0)
Dt_mis_labels = torch.cat(misclassified_labels, dim=0)

print(f"총 훈련 샘플 수: {total_samples}")
print(f"틀린 예측 수: {incorrect_samples}")
print(f"Dt_mis shape: {Dt_mis_inputs.shape}, {Dt_mis_labels.shape}")

torch.save(Dt_mis_inputs, 'Dt_mis_inputs.pt')
torch.save(Dt_mis_labels, 'Dt_mis_labels.pt')

def fgsm_attack(model, loss_fn, images, labels, epsilon):
    images.requires_grad = True
    outputs = model(images)
    loss = loss_fn(outputs, labels)
    model.zero_grad()
    loss.backward()
    perturbed_images = images + epsilon * images.grad.sign()
    return torch.clamp(perturbed_images, -1, 1)

epsilon = 0.1
Dt_mis_inputs_fgsm = fgsm_attack(base_model, criterion, Dt_mis_inputs.clone().to(device), Dt_mis_labels.to(device), epsilon)
Dt_mis_inputs_fgsm = Dt_mis_inputs_fgsm.detach().cpu()
torch.save(Dt_mis_inputs_fgsm, 'Dt_mis_inputs_fgsm.pt')
print("FGSM 공격 데이터 생성 완료")

model_aprime = BaseModel().to(device)
model_aprime.load_state_dict(torch.load('base_model.pth'))

Dt_mis_dataset = TensorDataset(Dt_mis_inputs_fgsm, Dt_mis_labels)
Dt_mis_loader = DataLoader(Dt_mis_dataset, batch_size=64, shuffle=True)

optimizer = optim.Adam(model_aprime.parameters(), lr=0.001)
num_epochs = 10
model_aprime.train()
for epoch in range(num_epochs):
    running_loss = 0.0
    for inputs, labels in Dt_mis_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model_aprime(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    print(f"[A' Epoch {epoch+1}] Loss: {running_loss:.3f}")

torch.save(model_aprime.state_dict(), 'a_prime_model.pth')
print("A' 모델 저장 완료: a_prime_model.pth")

n_iter = 30
model_aprime.train()  # Dropout 활성화
all_preds = []
for _ in range(n_iter):
    with torch.no_grad():
        outputs = model_aprime(Dt_mis_inputs_fgsm.to(device))
        probs = torch.softmax(outputs, dim=1)
        all_preds.append(probs.cpu())

all_preds = torch.stack(all_preds)  # [n_iter, N, C]
mean_preds = all_preds.mean(dim=0)
std_preds = all_preds.std(dim=0)
uncertainty = std_preds.mean(dim=1)  # 샘플별 불확실성

pred_classes = mean_preds.argmax(dim=1)
accuracy = (pred_classes == Dt_mis_labels).float().mean().item()
print(f"MC Dropout 정확도: {accuracy * 100:.2f}%")
print(f"평균 불확실성: {uncertainty.mean().item():.4f}")

topk = torch.topk(uncertainty, 5)
print("상위 5개 불확실성 높은 샘플 (불확실성 값):")
print(topk.values)

"""
def mc_dropout_predict(model, inputs, n_iter=20):
    model.train()  # Dropout 활성화
    preds = []
    for _ in range(n_iter):
        with torch.no_grad():
            outputs = model(inputs.to(device))
            preds.append(torch.softmax(outputs, dim=1).cpu())
    preds = torch.stack(preds)
    mean_preds = preds.mean(dim=0)
    std_preds = preds.std(dim=0)
    return mean_preds, std_preds

sample_inputs = Dt_mis_inputs_fgsm[:10]  # 일부 샘플
mean_preds, std_preds = mc_dropout_predict(model_aprime, sample_inputs)
print("MC Dropout Prediction Mean:\n", mean_preds)
print("MC Dropout Prediction Std:\n", std_preds)
"""